[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.17.0"
egui-winit = "0.17.0"
vulkano = "0.29.0"
vulkano-shaders = "0.29.0"
winit = "0.26"

[dev-dependencies]
egui_demo_lib = "0.17.0"
vulkano-win = "0.29.0"